-- MySQL Script generated by MySQL Workbench
-- Fri Oct 29 19:17:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema audio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema audio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `audio` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `audio` ;

-- -----------------------------------------------------
-- Table `audio`.`albums`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`albums` (
  `album_id` BIGINT NOT NULL AUTO_INCREMENT,
  `album_name` VARCHAR(45) NOT NULL,
  `album_info` VARCHAR(600) NULL DEFAULT NULL,
  `album_img` VARCHAR(300) NULL DEFAULT 'E:/EPAM/HoweWork/EPAM/FinalProject/images/user/unknown.png',
  PRIMARY KEY (`album_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 98
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`authors` (
  `author_id` BIGINT NOT NULL AUTO_INCREMENT,
  `author_name` VARCHAR(45) NOT NULL,
  `author_img` VARCHAR(300) NULL DEFAULT 'E:/EPAM/HoweWork/EPAM/FinalProject/images/user/unknown.png',
  `author_info` VARCHAR(600) NULL DEFAULT NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`user_roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`user_roles` (
  `user_role_id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `user_role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`user_statuses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`user_statuses` (
  `user_status_id` TINYINT(1) NOT NULL AUTO_INCREMENT,
  `user_status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`user_status_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`users` (
  `user_id` BIGINT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(80) NOT NULL,
  `password` VARCHAR(40) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `user_created` TIMESTAMP NOT NULL,
  `balance` DECIMAL(5,0) NOT NULL DEFAULT '0',
  `user_roles_user_role_id` TINYINT(1) NOT NULL,
  `user_statuses_user_status_id` TINYINT(1) NOT NULL,
  `bonus` DECIMAL(5,0) NOT NULL DEFAULT '0',
  `user_img` VARCHAR(600) NOT NULL DEFAULT 'E:/EPAM/HoweWork/EPAM/FinalProject/images/user/unknown.png',
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_user_roles1_idx` (`user_roles_user_role_id` ASC) VISIBLE,
  INDEX `fk_users_user_statuses1_idx` (`user_statuses_user_status_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_user_roles1`
    FOREIGN KEY (`user_roles_user_role_id`)
    REFERENCES `audio`.`user_roles` (`user_role_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_users_user_statuses1`
    FOREIGN KEY (`user_statuses_user_status_id`)
    REFERENCES `audio`.`user_statuses` (`user_status_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 797
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`comments` (
  `comment_id` BIGINT NOT NULL AUTO_INCREMENT,
  `comment` VARCHAR(500) NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  `albums_album_id` BIGINT NOT NULL,
  PRIMARY KEY (`comment_id`),
  INDEX `fk_comments_users1_idx` (`users_user_id` ASC) VISIBLE,
  INDEX `fk_comments_albums1_idx` (`albums_album_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_albums1`
    FOREIGN KEY (`albums_album_id`)
    REFERENCES `audio`.`albums` (`album_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comments_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `audio`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 125
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`genres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`genres` (
  `genre_id` BIGINT NOT NULL AUTO_INCREMENT,
  `genre_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`genre_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`orders` (
  `order_id` BIGINT NOT NULL AUTO_INCREMENT,
  `order_date` TIMESTAMP NOT NULL,
  `users_user_id` BIGINT NOT NULL,
  PRIMARY KEY (`order_id`),
  INDEX `fk_orders_users1_idx` (`users_user_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_user_id`)
    REFERENCES `audio`.`users` (`user_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 111
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`songs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`songs` (
  `song_id` BIGINT NOT NULL AUTO_INCREMENT,
  `song_name` VARCHAR(45) NOT NULL,
  `song_price` DECIMAL(5,0) NOT NULL,
  `genres_genre_id` BIGINT NOT NULL,
  `authors_author_id` BIGINT NOT NULL,
  `albums_album_id` BIGINT NOT NULL,
  PRIMARY KEY (`song_id`),
  INDEX `fk_songs_genres1_idx` (`genres_genre_id` ASC) VISIBLE,
  INDEX `fk_songs_authors1_idx` (`authors_author_id` ASC) VISIBLE,
  INDEX `fk_songs_albums1_idx` (`albums_album_id` ASC) VISIBLE,
  CONSTRAINT `fk_songs_albums1`
    FOREIGN KEY (`albums_album_id`)
    REFERENCES `audio`.`albums` (`album_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_songs_authors1`
    FOREIGN KEY (`authors_author_id`)
    REFERENCES `audio`.`authors` (`author_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_songs_genres1`
    FOREIGN KEY (`genres_genre_id`)
    REFERENCES `audio`.`genres` (`genre_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `audio`.`songs_has_orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `audio`.`songs_has_orders` (
  `songs_song_id` BIGINT NOT NULL,
  `orders_order_id` BIGINT NOT NULL,
  UNIQUE INDEX `uniq` (`songs_song_id` ASC, `orders_order_id` ASC) VISIBLE,
  INDEX `fk_songs_has_orders_songs1_idx` (`songs_song_id` ASC) VISIBLE,
  INDEX `fk_songs_has_orders_orders1_idx` (`orders_order_id` ASC) VISIBLE,
  CONSTRAINT `fk_songs_has_orders_orders1`
    FOREIGN KEY (`orders_order_id`)
    REFERENCES `audio`.`orders` (`order_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_songs_has_orders_songs1`
    FOREIGN KEY (`songs_song_id`)
    REFERENCES `audio`.`songs` (`song_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
